name: dns-keepalive

# The "normalnet" needs to be lexicographically before dnsnet in order to be the
# default gateway - this is... stupid, and defining "gw_priority" has only been
# introduced in (as of 2025-03-04) bleeding-edge docker compose.

networks:
  a_normalnet:
    driver: bridge

  dnsnet:
    driver: ipvlan
    driver_opts:
      parent: eth0.53
      mode: l3s
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

services:
  keepalived:
    image: visibilityspots/keepalived:latest
    network_mode: host
    depends_on:
      - unbound1
      - unbound2
    volumes:
      - ./keepalived.conf:/etc/keepalived/keepalived.conf:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST

  unbound1:
    image: klutchell/unbound
    restart: unless-stopped
    hostname: unbound1
    networks:
      dnsnet:
        ipv4_address: 192.168.100.2
      a_normalnet:
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound.override.conf:/etc/unbound/custom.conf.d/override.conf:ro

  unbound2:
    image: klutchell/unbound
    restart: unless-stopped
    hostname: unbound2
    networks:
      dnsnet:
        ipv4_address: 192.168.100.3
      a_normalnet:
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound.override.conf:/etc/unbound/custom.conf.d/override.conf:ro

  alpine-test:
    build: ../docker/alpine-test
    hostname: alpine-test
    init: true
    command: ["/root/watcher.sh"]
    depends_on:
      - keepalived
#      - unbound1
#      - unbound2
    #NOTE: these capabilities are not needed for normal functionality, just for debugging purposes.
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      a_normalnet:
#        gw_priority: 1 # not yet :(
      dnsnet:
    dns:
      - 192.168.100.100
      - 1.0.0.1 # cloudflare fallback
